---
version: "2"

run:
  tests: true

linters:
  default: all
  disable:
    # restrictive
    - exhaustruct
    - varnamelen
    - nlreturn
    - funlen
    - nonamedreturns
    - gochecknoglobals
    - wsl
    - nakedret
    - err113
    # possibly enable later
    - wrapcheck
    - cyclop
    - noctx
    - forcetypeassert
    - gocritic
    - nestif

  settings:
    depguard:
      rules:
        main:
          list-mode: strict
          files:
            - $all
          allow:
            - $gostd
            - golang.org/x/tools
            - github.com/soypat/rebed
    gosec:
      excludes:
        - G114 # server without timeout
        - G304 # file inclusion

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    golines:
      max-len: 120

issues:
  fix: true

output:
  formats:
    text:
      path: stdout
    tab:
      path: golangci-lint.out
      colors: false
    html:
      path: golangci-lint.out.html
